//Add class with filter effects

$(document).ready(function() {

    var image = $("img");
    var btnSaturate = $(".btn-saturate");
    var saturate = "saturate";
    var btnSaturotate = $(".btn-saturotate");
    var saturotate = "saturotate";
    var btnRotamatrix = $(".btn-rotamatrix");
    var rotamatrix = "rotamatrix";
    var btnTablen = $(".btn-tablen");
    var table = "tablen";
    var btnMultitable = $(".btn-multitable");
    var multitable = "multitable";
    var btnDishue = $(".btn-dishue");
    var dishue = "dishue";
    var btnMatrix = $(".btn-matrix");
    var matrix = "matrix";
    var btnMatrix2 = $(".btn-matrix-dos");
    var matrix2 = "matrix-dos";
    var btnHueRotate = $(".btn-hueRotate");
    var huerotate = "huerotate";
    var btnLuminance = $(".btn-luminance");
    var luminance = "luminance";
    var btnDiscrete = $(".btn-discrete");
    var discrete = "discrete";
    var btnDiscrete2 = $(".btn-discrete-dos");
    var discrete2 = "discrete-dos";
    var btnTable = $(".btn-table");
    var table = "table";
    var btnTable2 = $(".btn-table-dos");
    var table2 = "table-dos";
    var btnIdentity = $(".btn-identity");
    var identity = "identity";
    var btnLinear = $(".btn-linear");
    var linear = "linear";
    var btnGamma = $(".btn-gamma");
    var gamma = "gamma";
    var btnTurbelence = $(".btn-turbulence");
    var turbulence = "turbulence";
    var btnSepia = $(".btn-sepia");
    var sepia = "sepia";
    var btnTurbuMap = $(".btn-turbu-map");
    var turbumap = "turbu-map";
    var btnMatrix = $(".btn-con-matrix-uno");
    var fematrix = "fematrix-uno";
    var btnMatrix2 = $(".btn-con-matrix-dos");
    var fematrix2 = "fematrix-dos";
    var btnMap = $(".btn-map-uno");
    var mapUno = "map-uno";
    var btnMap2 = $(".btn-map-dos");
    var mapDos = "map-dos";
    var btnBlur = $(".btn-blur-uno");
    var blur = "blur-uno";
    var btnBlur2 = $(".btn-blur-dos");
    var blur2 = "blur-dos";
    var btnBlur3 = $(".btn-blur-tres");
    var blur3 = "blur-tres";
    var btnMorpho = $(".btn-morpho-uno");
    var morpho = "morpho-uno";
    var btnMorpho2 = $(".btn-morpho-dos");
    var morpho2 = "morpho-dos";
    var btnMorpho3 = $(".btn-morpho-tres");
    var morpho3 = "morpho-tres";
    var btnMorpho4 = $(".btn-morpho-cuatro");
    var morpho4 = "morpho-cuatro";

    function addFilter(button, image, filter) {
        $(button).click(function() {
            $(image).removeClass().addClass(saturate);
        });
    }

    addFilter(btnSaturate, image, saturate);
    addFilter(btnSaturotate, image, saturotate);
    addFilter(btnRotamatrix, image, rotamatrix);
    addFilter(btnTablen, image, tablen);
    addFilter(btnMultitable, image, multitable);
    addFilter(btnDishue, image, dishue);
    addFilter(btnMatrix, image, matrix);
    addFilter(btnMatrix2, image, matrix2);
    addFilter(btnHueRotate, image, huerotate);
    addFilter(btnLuminance, image, luminance);
    addFilter(btnDiscrete, image, discrete);
    addFilter(btnDiscrete2, image, discrete2);
    addFilter(btnTable, image, table);
    addFilter(btnTable2, image, table2);
    addFilter(btnIdentity, image, identity);
    addFilter(btnLinear, image, linear);
    addFilter(btnGamma, image, gamma);
    addFilter(btnTurbelence, image, turbulence);
    addFilter(btnSepia, image, sepia);
    addFilter(btnTurbuMap, image, turbumap);
    addFilter(btnMatrix, image, fematrix);
    addFilter(btnMatrix2, image, fematrix2);
    addFilter(btnMap, image, mapUno);
    addFilter(btnMap2, image, mapDos);
    addFilter(btnBlur, image, blur);
    addFilter(btnBlur2, image, blur2);
    addFilter(btnBlur3, image, blur3);
    addFilter(btnMorpho, image, morpho);
    addFilter(btnMorpho2, image, morpho2);
    addFilter(btnMorpho3, image, morpho3);
    addFilter(btnMorpho4, image, morpho4);
});